"""Add favorite beaches association table

Revision ID: 248445def7ad
Revises: c298e7b5ac86
Create Date: 2024-09-01 20:01:53.997899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248445def7ad'
down_revision: Union[str, None] = 'c298e7b5ac86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_beaches',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('beach_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beach_id'], ['beaches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_beaches')
    # ### end Alembic commands ###
