"""Add onesignal_player_id to users table

Revision ID: 8c813947359b
Revises: 248445def7ad
Create Date: 2024-09-02 12:04:09.678147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c813947359b'
down_revision: Union[str, None] = '248445def7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onesignal_player_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onesignal_player_id')
    # ### end Alembic commands ###
