"""Add created_at and updated_at to Beach model

Revision ID: c298e7b5ac86
Revises: 8ed71d8b85bd
Create Date: 2024-08-30 17:56:32.802103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c298e7b5ac86"
down_revision: Union[str, None] = "8ed71d8b85bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "beaches",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "beaches", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("beaches", "updated_at")
    op.drop_column("beaches", "created_at")
    # ### end Alembic commands ###
